apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-validation
spec:
  replicas: 3   # 🔥 run 3 replicas for horizontal scaling
  selector:
    matchLabels:
      app: erp-validation
  template:
    metadata:
      labels:
        app: erp-validation
    spec:
      containers:
      - name: erp-validation
        image: erp-validation:latest   # your Docker image
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: erp-validation-service
spec:
  selector:
    app: erp-validation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
